### ISSUE TITLE
How to add plugins in grafana container image 

### ISSUE THREAD

**Issue by j-regis** [bitnami/bitnami-docker-grafana#2]
Hello,

my question is simple. How to add plugins in the grafana docker image ? We are using Azure Container Instance and want to add log analytics plugins which is not bundle in the bitnami image.

Regards.

**Comment by juan131** [comment]
You can indicate the plugins to install using the env. variable **GF_INSTALL_PLUGINS**, see the piece of code below:

https://github.com/bitnami/bitnami-docker-grafana/blob/master/5/debian-9/rootfs/run.sh#L9

@tompizmor why isn't this feature documented in the **README.md** file?
