### ISSUE TITLE
[Bug] Broken image compatibility with grafana-operator

### ISSUE THREAD

**Issue by tippl** [bitnami/bitnami-docker-grafana#22]
**Description**

When using grafana image 8.3.3 in grafana-operator, provisioning of grafana datasources stops working. Version 8.1.5 works as intended.

Looks like entrypoint.sh never runs the `/opt/bitnami/scripts/grafana/setup.sh` which ensures operator compatibility by making symlinks in grafana configuration.

This seems to be because grafana operator actually runs the container with CMD set to `-config=/etc/grafana/grafana.ini` instead of `/opt/bitnami/scripts/grafana/run.sh` which this line of code expects.
https://github.com/bitnami/bitnami-docker-grafana/blob/master/8/debian-10/rootfs/opt/bitnami/scripts/grafana/entrypoint.sh#L29

Reporting here because it is a regression in the docker image and not caused by helm chart nor changes in grafana-operator.

**Steps to reproduce the issue:**

1. Install grafana operator version 2.0.4 (not working)
2. run: `kubectl exec grafana-deployment-... -it -- bash`
3. run: `ls -la /opt/bitnami/grafana/conf/`
4. Directory `provisioning` is not a symlink

**Describe the results you expected:**

1. Install grafana operator version 1.1.4 (working)
2. run: `kubectl exec grafana-deployment-... -it -- bash`
3. run: `ls -la /opt/bitnami/grafana/conf/`
4. Directory `provisioning` is now a symlink to /etc

**Additional information you deem important (e.g. issue happens only occasionally):**

As described above, running kubectl describe on the pod returns this:
```
    Args:
      -config=/etc/grafana/grafana.ini
```

**Version**

8.3.3-debian-10-r16 - not working
8.1.5-debian-10-r14 - working

**Comment by d-m** [comment]
I'm running into the same issue with the grafana-operator and `GrafanaDataSource` resources and just chased the same issue back to here as well.

**Comment by carrodher** [comment]
Thanks for reporting this issue and creating the associated PR. The team will review it and provide feedback during the following days. Thanks again
