### ISSUE TITLE
[bitnami-docker-grafana] Query regarding chart/dockerfile user 1001, but container user 999?

### ISSUE THREAD

**Issue by greg-a-atkinson** [bitnami/bitnami-docker-grafana#24]
**Query regarding chart/dockerfile user 1001, but container user 999?**

Just a query. Is it intentional that `bitnami-docker-grafana/8/debian-10/Dockerfile` specifies `USER 1001` and the `bitnami/grafana` chart specifies `grafana.containerSecurityContext.runAsUser: 1001`, while the `grafana` user within the container has uid `999`?

**Steps to reproduce the issue:**

1. Open a shell into the container: `docker run --rm -it --entrypoint /bin/bash bitnami/grafana:8.3.3-debian-10-r27`
2. Review container's `grafana` user:

```
I have no name!@a9059fceef2e:/opt/bitnami/grafana/conf$ ls -la /opt/bitnami/grafana/data /opt/bitnami/grafana/logs
/opt/bitnami/grafana/data:
total 12
drwxrwxr-x 3 grafana root 4096 Jan 11 11:37 .
drwxrwxr-x 1 root    root 4096 Jan 11 11:37 ..
drwxrwxr-x 2 grafana root 4096 Jan 11 11:37 plugins

/opt/bitnami/grafana/logs:
total 8
drwxrwxr-x 2 grafana root 4096 Jan 11 11:37 .
drwxrwxr-x 1 root    root 4096 Jan 11 11:37 ..

I have no name!@a9059fceef2e:/opt/bitnami/grafana/conf$ grep grafana /etc/passwd
grafana:x:999:999::/home/grafana:/bin/sh
```
3. Review container's run-as user:
```
I have no name!@a9059fceef2e:/opt/bitnami/grafana/conf$ whoami
whoami: cannot find name for user ID 1001
```

**Describe the results you received:**

Dockerfile user does not have the same uid as container user.

**Describe the results you expected:**

Dockerfile user has the same uid as the container user.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

n/a

**Comment by marcosbc** [comment]
Yes, it is expected. That way we are forcing the container to run with an arbitrary UID by default, which is the recommended approach to run non-root containers. That way it is also compatible with environments like OpenShift by default, where the UID is variable.

**Comment by greg-a-atkinson** [comment]
Thanks for confirming.
