### ISSUE TITLE
Build image for a specific tag

### ISSUE THREAD

**Issue by nicolaerosia** [bitnami/bitnami-docker-grafana#25]
### Name and Version

bitnami/grafana

### What is the problem this feature will solve?

Building a specific commit id

### What is the feature you are proposing to solve the problem?

I would like to be able to build a specific git commit of upstream grafana, or even my own repo.
How can I do that?

**Comment by juan131** [comment]
Hi @nicolaerosia 

The Dockerfile used to build this image is public, see:

- https://github.com/bitnami/bitnami-docker-grafana/blob/master/8/debian-10/Dockerfile

Feel free to replace line below and download/package the specific Grafana version you're interested on:

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "grafana" "8.3.6-0" --checksum 71dfdc53d4f2e9e69bcc3b8683929a78d7162eebf40092f45637fa847b6631be
```

**Comment by nicolaerosia** [comment]
Hello,

component_unpack seems to download prebuilt packages from bitnami.
I dont see where the grafana source code is downloaded and built.

I want to be able to build any grafana git hash/tag, not only what bitnami has prebuilt.

Is the process of building components public?

**Comment by juan131** [comment]
Hi @nicolaerosia 

Sorry if I was not clear enough. I was not suggestion to use `component_unpack` and consume Bitnami packages. I was talking about substituting that line with your custom code/scripts to download/extract the specific Grafana version you're interested on. This custom code should do sth very similar to "component_unpack" when extracting Grafana (e.g. use the same folder: `/opt/bitnami/grafana`). The "component_unpack" code can be found below:

- https://github.com/bitnami/bitnami-docker-grafana/blob/master/8/debian-10/prebuildfs/opt/bitnami/scripts/libcomponent.sh#L23
