### ISSUE TITLE
Persistent storage azure

### ISSUE THREAD

**Issue by ChonoN** [bitnami/bitnami-docker-grafana#6]
Is there a way to add persistent storage when running as an azure web app?

**Comment by juan131** [comment]
Hi @ChonoN 

Are you using AKS? If that's the case you can install the Grafana chart on AKS and customize it to enable persistence (more info at https://bitnami.com/stack/grafana/helm and https://docs.bitnami.com/azure/get-started-aks/)

As you can see at the [Grafana chart README](https://github.com/bitnami/charts/blob/master/bitnami/grafana/README.md), you can enable persistence using the parameters below:


| Parameter                             | Description                                           | Default                    |
|---------------------------|------------------------------------|-------------------|
| persistence.enabled           | Enable persistence                              | `true`                      |
| presistence.storageClass  | Storage class to use with the PVC   | `nil`                         |
| persistence.accessMode  | Access mode to the PV                      | `ReadWriteOnce` |
| persistence.size                  | Size for the PV                                     | `10Gi`                      |

**Comment by ChonoN** [comment]
Hi @juan131 unfortunately not, I was using it in ASP form for the time being.

**Comment by juan131** [comment]
Hi @ChonoN 

So you're using [this solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/bitnami.grafana), right? I mean, a SingleVM running on Azure Cloud. If that's the case, please not on this GitHub repo we answer questions related to the Grafana container image, for questions related to the SingleVM, please visit Bitnami Community Forum at https://community.bitnami.com/

**Comment by ChonoN** [comment]
Hi @juan131 incorrect, I'm using the container image via App Service Plan.

**Comment by juan131** [comment]
I'm afraid I'm not familiar with the Azure App Service Plan. I understand it allows you to deploy container and VMs (to be used as your backend) on Azure using one of its services. 

Do you know if that's using [ACI](https://azure.microsoft.com/en-us/services/container-instances/) (Azure Container Instances) to deploy the container?

**Comment by ChonoN** [comment]
Hi @juan131 sorry for the delay in reply. No it deploys via another mechanism which is web app for containers.

**Comment by juan131** [comment]
Hi @ChonoN 

As i said I'm not familiar with this Azure service, you probably need to follow the steps described in the guide below:

- https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-serve-content-from-azure-storage

It explains how to add storage to your containers using Azure Storage. Please note that this Grafana image storage its data at `/opt/bitnami/grafana/data`, so you must mount your volumes at that mount point to ensure your Grafana data is persisted.
