### ISSUE TITLE
Please remove  GF_INSTALL_PLUGINS="grafana-image-renderer" addition at bc4f25463ef7a4d5b3c6a6120d8e063d217225ae

### ISSUE THREAD

**Issue by jjo** [bitnami/bitnami-docker-grafana#8]
**Description**

Added GF_INSTALL_PLUGINS="grafana-image-renderer" bc4f25463ef7a4d5b3c6a6120d8e063d217225ae heavily increases netio and final container usage,
from ~250MB from image to ~750MB after downloading it.

Please document the mechanics (GF_INSTALL_PLUGINS), but don't opinionate a default to it.

**Steps to reproduce the issue:**

1) Run the container as provided:
```
$ docker run --name=grafana -it --rm bitnami/grafana:6.7.2-debian-10-r20
[... several minutes until ready ...]

$ docker exec -it grafana du -sch /opt/bitnami/grafana/data/plugins
708M	/opt/bitnami/grafana/data/plugins
708M	total
```
2) Working around with nil env var:
```
docker run -e GF_INSTALL_PLUGINS="" --name=grafana -it --rm bitnami/grafana:6.7.2-debian-10-r20
$ docker run --name=grafana -it --rm bitnami/grafana:6.7.2-debian-10-r20
[... few seconds ...]

$ docker exec -it grafana du -sch /opt/bitnami/grafana/data/plugins
708M	/opt/bitnami/grafana/data/plugins
708M	total
```

**Describe the results you received:**

As per above

**Describe the results you expected:**

Container to be ready in a few seconds, without requiring any external network io, this can also heavily complicate airgapped deployments.

**Version**

`bitnami/grafana:6.7.2-debian-10-r20`

**Comment by juan131** [comment]
Hi @jjo 

This plugin is not compatible on those clusters that don't support IPv6. See https://github.com/bitnami/bitnami-docker-grafana#672-debian-10-r18

Before that revision, the plugins was included by default in the Grafana tarball, the one you download at https://github.com/bitnami/bitnami-docker-grafana/blob/master/6/debian-10/Dockerfile#L6. However, we had to stop shipping it by default (see https://github.com/bitnami/charts/issues/2352)

**Comment by jjo** [comment]
Understood, do not tho:
- this would impact most Kubernetes clusters ops/users: in its current form this is unusable, will keep crashlooping on failed readiness probes, unless the manifests force `GF_INSTALL_PLUGINS=""` on manifests
- requiring a 1/2GB download at startup by default is not a good practice IMO, I'd rather let the users potentially impacted by previous default (PKS's iiuc?) to set that envvar themselves
- there's no docker caching to help with above
- it would be a true show-stopper for airgapped deployments (ie deployments w/o limited external connectivity by org security polices)

**Comment by juan131** [comment]
Hi everyone,

I just wanted to share with you that we released a new container [Grafana Image Renderer](https://github.com/bitnami/bitnami-docker-grafana-image-renderer) that you can use to run the rendering service on a different container.

Please also note that `grafana-image-renderer` is not installed by default anymore in the Grafana image. Find more information in the links below:

- https://github.com/bitnami/bitnami-docker-grafana#grafana-image-renderer-plugin
- https://github.com/bitnami/bitnami-docker-grafana#673-debian-10-r28
