### ISSUE TITLE
Question regarding SMTP configuration and/or custom configuration override

### ISSUE THREAD

**Issue by andrei-dascalu** [bitnami/bitnami-docker-grafana#9]
**Description**

I am trying to setup smtp configuration, though according to the container documentation, only user/pass are exposed while the smtp host seem to be configurable only via a customized configuration.

I've added a custom.ini mapped to the expected path at `/opt/bitnami/grafana/conf/custom.ini` and it has the expected contents - however Grafana still says that SMTP is not configured (the settings used are tested and working in other SMTP applications)

custom.ini contents

```
[smtp]
enabled = true
host = smtp.eu.mailgun.org:587
user = postmaster@mailgun.<whatever>.com
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = <whatever>
;cert_file =
;key_file =
;skip_verify = false
from_address = noreply-grafana@<whatever>.com
from_name = Grafana
# EHLO identity in SMTP dialog (defaults to instance_name)
ehlo_identity = grafana.<whatever>.com

[emails]
welcome_email_on_sign_up = true
;templates_pattern = emails/*.html
```

**Steps to reproduce the issue:**

1. create custom.ini as per above (using a smtp configuration other than for localhost -> remote smtp server with TLS port)
2. start grafana container and mount custom file to custom configuration folder
3. login to grafana and invite a user

**Describe the results you received:**

2 errors saying that mail send failed & another saying that SMTP is not configured

**Describe the results you expected:**

user receives email (or at least no error)

**Additional information you deem important (e.g. issue happens only occasionally):**

The Grafana documentation mentions that custom configuration should be done via grafana.ini OR custom.ini, however it's not clear to me exactly how the loading is done and whether the workings of the Bitnami image are different in that regard (or how to test whether the ini was actually loaded). I've tried the same on the official Grafana image and it's working as expected.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 8
  Paused: 0
  Stopped: 14
 Images: 396
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.811GiB
 Name: docker-desktop
 ID: CEZ5:MD2K:ZBJO:J7DR:WDTK:TJBQ:QB25:BRX7:VH2B:BF3S:TUTA:KF6H
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 107
  Goroutines: 104
  System Time: 2020-06-15T09:00:06.0295877Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  dockerhub.dgtls.com:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details: local machine / laptop **

**Comment by marcosbc** [comment]
Hi @andrei-dascalu, you're right. I was able to reproduce this on our side and the issue is our documentation (README.md) is wrong as it should mention "grafana.ini" instead of "custom.ini". When I fixed the mount path, it started working.

We'll update the README on our side to make sure it is correct. In the meantime, use the proper grafana.ini file and it should work for you. Thanks!
